// Starter documents offered in the Templates modal. Pure data — no runtime
// dependencies, safe to import from client components.

export const TEMPLATES = [
  {
    id: "meeting-notes",
    name: "Meeting Notes",
    description: "Capture who was there, what was decided, and every follow-up with an owner.",
    icon: "notebook",
    html: `<h1>[Team / Project] Meeting — [Date]</h1><p><strong>Facilitator:</strong> [Name] · <strong>Note-taker:</strong> [Name] · <strong>Duration:</strong> [Length]</p><h2>Present</h2><ul><li>[Name], [Role]</li><li>[Name], [Role]</li><li>[Name], [Role]</li></ul><p><em>Regrets: [invitees who could not attend]</em></p><h2>Topics Covered</h2><ol><li>[First topic]</li><li>[Second topic]</li><li>[Third topic]</li></ol><h2>Key Takeaways</h2><ul><li>[The single most important thing the group learned or aligned on]</li><li>[Another insight, update, or piece of context worth keeping]</li></ul><h2>Decisions</h2><table><tbody><tr><th><p>Decision</p></th><th><p>Rationale</p></th><th><p>Decided by</p></th></tr><tr><td><p>[What was agreed]</p></td><td><p>[Why this option won]</p></td><td><p>[Name or group]</p></td></tr></tbody></table><h2>Follow-ups</h2><table><tbody><tr><th><p>Task</p></th><th><p>Assigned to</p></th><th><p>Deadline</p></th></tr><tr><td><p>[What needs to happen]</p></td><td><p>[Name]</p></td><td><p>[Date]</p></td></tr><tr><td><p>[What needs to happen]</p></td><td><p>[Name]</p></td><td><p>[Date]</p></td></tr></tbody></table><h2>Parked for Later</h2><ul><li>[Topic raised but deliberately deferred — revisit on [Date]]</li></ul><p><strong>Next meeting:</strong> [Date and time] — [what it will focus on].</p>`,
  },
  {
    id: "status-update",
    name: "Project Status Update",
    description: "Stakeholder report with RAG health, progress, blockers, and asks at a glance.",
    icon: "activity",
    html: `<h1>Status Report: [Project Name]</h1><p><strong>Period:</strong> [Week of Date] · <strong>Author:</strong> [Name] · <strong>Overall health:</strong> [Green / Amber / Red]</p><h2>Health at a Glance</h2><table><tbody><tr><th><p>Area</p></th><th><p>Status</p></th><th><p>Comment</p></th></tr><tr><td><p>Scope</p></td><td><p>[Green]</p></td><td><p>[No change since last report]</p></td></tr><tr><td><p>Schedule</p></td><td><p>[Amber]</p></td><td><p>[What slipped and the recovery plan]</p></td></tr><tr><td><p>Budget</p></td><td><p>[Green]</p></td><td><p>[Spend versus plan]</p></td></tr><tr><td><p>Team</p></td><td><p>[Green]</p></td><td><p>[Capacity, morale, hiring]</p></td></tr></tbody></table><h2>Done This Period</h2><ul><li>[Shipped, finished, or resolved item — link to evidence where possible]</li><li>[Another completed item]</li></ul><h2>Up Next</h2><ul><li>[Priority for the coming period and who is driving it]</li><li>[Second priority]</li></ul><h2>Blockers &amp; Asks</h2><table><tbody><tr><th><p>Blocker</p></th><th><p>Impact if unresolved</p></th><th><p>Ask</p></th></tr><tr><td><p>[What is stuck]</p></td><td><p>[The date or deliverable at risk]</p></td><td><p>[The specific help or decision needed, and from whom]</p></td></tr></tbody></table><h2>Decisions Needed</h2><ul><li>[Decision, the options on the table, and the date it must be made by]</li></ul><p><em>Questions about this report? Contact [Name] on [channel or email].</em></p>`,
  },
  {
    id: "product-one-pager",
    name: "Product One-Pager",
    description: "Pitch a product or feature on one page: problem, proposal, metrics, non-goals.",
    icon: "package",
    html: `<h1>[Product / Feature Name]</h1><p><strong>Owner:</strong> [Name] · <strong>Team:</strong> [Team] · <strong>Status:</strong> [Draft / In review / Approved] · <strong>Last updated:</strong> [Date]</p><h2>Problem</h2><p>[Describe the pain in the user's own words. Who hits it, how often, and what it costs them. If you have evidence — support tickets, churn data, interview quotes — cite it here.]</p><h2>Audience</h2><ul><li><strong>[Primary user]</strong> — [their goal and the moment this product meets them]</li><li><strong>[Secondary user]</strong> — [how they benefit differently]</li></ul><h2>Proposal</h2><p>[What we will build, in plain language. Lead with the user-visible behavior, not the implementation. One paragraph — if it needs more, it needs a full spec.]</p><h2>Why Now</h2><p>[The trigger: a customer commitment, a competitive move, a dependency that just landed, or a window that is closing.]</p><h2>Success Metrics</h2><table><tbody><tr><th><p>Metric</p></th><th><p>Today</p></th><th><p>Target</p></th></tr><tr><td><p>[Primary metric]</p></td><td><p>[Baseline]</p></td><td><p>[Goal by [date]]</p></td></tr><tr><td><p>[Guardrail metric]</p></td><td><p>[Baseline]</p></td><td><p>[Must not regress]</p></td></tr></tbody></table><h2>Non-Goals</h2><ul><li>[Tempting adjacent problem this deliberately does not solve]</li><li>[Scope cut to keep the first version shippable]</li></ul><h2>Open Questions</h2><ul><li>[Unresolved question] — owner: [Name]</li><li>[Unresolved question] — owner: [Name]</li></ul><h2>Rough Milestones</h2><table><tbody><tr><th><p>Milestone</p></th><th><p>Target</p></th></tr><tr><td><p>[Design review]</p></td><td><p>[Date]</p></td></tr><tr><td><p>[Beta with [N] customers]</p></td><td><p>[Date]</p></td></tr><tr><td><p>[General availability]</p></td><td><p>[Date]</p></td></tr></tbody></table>`,
  },
  {
    id: "press-release",
    name: "Press Release",
    description: "Announce news in standard press format: headline, dateline, quotes, boilerplate.",
    icon: "megaphone",
    html: `<p><strong>FOR IMMEDIATE RELEASE</strong></p><h1>[Company] [Launches / Announces / Partners With] [the News]</h1><p><em>[Sub-headline: one sentence adding the why-it-matters angle to the headline.]</em></p><p><strong>[City, Country] — [Month Day, Year]</strong> — [Company], [a one-phrase descriptor of what the company does], today announced [the news in one sentence: what is launching or changing, for whom, and when it is available].</p><p>[Second paragraph: the substance. What problem does this address, what exactly is new, and the two or three details a journalist would need to cover it accurately.]</p><p>"[A quote that adds perspective rather than restating the announcement — why now, why it matters, what it unlocks]," said <strong>[Spokesperson Name]</strong>, [Title] at [Company]. "[Optional second sentence of the quote.]"</p><p>[Third paragraph: supporting proof — customer traction, data points, pricing, availability dates, or partner details.]</p><p>"[Optional quote from a customer or partner lending outside credibility]," said <strong>[Name]</strong>, [Title] at [Partner Company].</p><h2>About [Company]</h2><p>[Boilerplate: two or three sentences on what the company does, who it serves, and its footprint — the paragraph you close every release with.] Learn more at [website.example.com].</p><h2>Media Contact</h2><p>[Contact Name]<br />[Title], [Company]<br />[press@example.com] · [+1 555 000 0000]</p><p><strong>###</strong></p>`,
  },
  {
    id: "statement-of-work",
    name: "Statement of Work",
    description: "Scope a client engagement with deliverables, acceptance terms, fees, and signatures.",
    icon: "handshake",
    html: `<h1>Statement of Work</h1><p><strong>SOW No.:</strong> [001] · <strong>Effective date:</strong> [Date]</p><p>This Statement of Work is entered into between <strong>[Provider Name]</strong> ("Provider") and <strong>[Client Name]</strong> ("Client") and is governed by the master services agreement between the parties dated [Date], if one exists.</p><h2>1. Project Overview</h2><p>[Two or three sentences describing the engagement: the outcome the Client wants, the approach the Provider will take, and the expected duration.]</p><h2>2. Scope of Services</h2><ul><li>[Service or workstream one — what the Provider will actually do]</li><li>[Service or workstream two]</li><li>[Service or workstream three]</li></ul><p><strong>Out of scope:</strong> [work explicitly excluded — anything listed here requires a signed change order].</p><h2>3. Deliverables &amp; Acceptance</h2><table><tbody><tr><th><p>Deliverable</p></th><th><p>Acceptance criteria</p></th><th><p>Target date</p></th></tr><tr><td><p>[Deliverable one]</p></td><td><p>[How the Client will judge it complete]</p></td><td><p>[Date]</p></td></tr><tr><td><p>[Deliverable two]</p></td><td><p>[How the Client will judge it complete]</p></td><td><p>[Date]</p></td></tr></tbody></table><p>The Client will review each deliverable within [5] business days of receipt. A deliverable with no written feedback inside that window is deemed accepted.</p><h2>4. Fees &amp; Payment Schedule</h2><table><tbody><tr><th><p>Milestone</p></th><th><p>Amount</p></th><th><p>Invoiced</p></th></tr><tr><td><p>Execution of this SOW</p></td><td><p>[Amount]</p></td><td><p>On signing</p></td></tr><tr><td><p>[Milestone]</p></td><td><p>[Amount]</p></td><td><p>[On delivery / date]</p></td></tr></tbody></table><p>Invoices are payable within [15] days. Expenses require the Client's prior written approval and are billed at cost.</p><h2>5. Assumptions</h2><ul><li>[Access, content, or approvals the Client will provide — name them]</li><li>[Feedback turnaround the schedule depends on]</li></ul><h2>6. Changes</h2><p>Either party may propose a change in writing. Work on a change begins only after both parties sign a change order describing its impact on scope, schedule, and fees.</p><h2>7. Signatures</h2><table><tbody><tr><th><p>For the Provider</p></th><th><p>For the Client</p></th></tr><tr><td><p>Name: [Name]<br />Title: [Title]<br />Signed: ______________________<br />On: [Date]</p></td><td><p>Name: [Name]<br />Title: [Title]<br />Signed: ______________________<br />On: [Date]</p></td></tr></tbody></table>`,
  },
  {
    id: "invoice",
    name: "Invoice",
    description: "Bill a client with itemized charges, a running summary, and payment instructions.",
    icon: "receipt",
    html: `<h1>Invoice [INV-001]</h1><p><strong>Issued:</strong> [Date] · <strong>Payment due:</strong> [Date] · <strong>Currency:</strong> [USD]</p><h3>Issued by</h3><p><strong>[Your Business Name]</strong><br />[Street Address], [City]<br />[Email] · [Phone] · [Tax or VAT ID]</p><h3>Billed to</h3><p><strong>[Client Company]</strong><br />Attn: [Contact Person]<br />[Street Address], [City]<br />[Email]</p><h2>Charges</h2><table><tbody><tr><th><p>Item</p></th><th><p>Details</p></th><th><p>Quantity</p></th><th><p>Unit price</p></th><th><p>Line total</p></th></tr><tr><td><p>[Service name]</p></td><td><p>[Short description of the work]</p></td><td><p>[1]</p></td><td><p>[100.00]</p></td><td><p>[100.00]</p></td></tr><tr><td><p>[Service name]</p></td><td><p>[Short description of the work]</p></td><td><p>[2]</p></td><td><p>[80.00]</p></td><td><p>[160.00]</p></td></tr></tbody></table><h2>Summary</h2><table><tbody><tr><th><p>Line</p></th><th><p>Amount</p></th></tr><tr><td><p>Subtotal</p></td><td><p>[260.00]</p></td></tr><tr><td><p>Discount</p></td><td><p>[0.00]</p></td></tr><tr><td><p>Tax ([Rate]%)</p></td><td><p>[26.00]</p></td></tr><tr><td><p><strong>Total due</strong></p></td><td><p><strong>[286.00]</strong></p></td></tr></tbody></table><h2>Payment Instructions</h2><ul><li><strong>Bank transfer:</strong> [Bank name], account [Number], routing or IBAN [Number]</li><li><strong>Reference:</strong> quote invoice number [INV-001] with your payment</li></ul><p><em>Terms: net [15] days from the issue date. Balances outstanding past the due date accrue a [2]% monthly late fee.</em></p>`,
  },
  {
    id: "job-offer",
    name: "Job Offer Letter",
    description: "Extend a formal employment offer covering role, compensation, and conditions.",
    icon: "briefcase",
    html: `<h1>Offer of Employment</h1><p>[Date]</p><p>Dear [Candidate First Name],</p><p>On behalf of everyone at <strong>[Company Name]</strong>, I am delighted to offer you the position of <strong>[Job Title]</strong> on our [Team Name] team. We were impressed by [something specific from your interviews], and we believe you will thrive here.</p><h2>The Role</h2><ul><li><strong>Title:</strong> [Job Title]</li><li><strong>Reporting to:</strong> [Manager Name], [Manager Title]</li><li><strong>Location:</strong> [Office location / Hybrid / Fully remote]</li><li><strong>Start date:</strong> [Date]</li><li><strong>Employment type:</strong> [Full-time / Part-time / Fixed-term]</li></ul><h2>Compensation &amp; Benefits</h2><ul><li><strong>Base salary:</strong> [Amount] per [year / month], paid [monthly / bi-weekly]</li><li><strong>Bonus:</strong> [target percentage, criteria, and payout timing — or remove this line]</li><li><strong>Equity:</strong> [number of options or RSUs and the vesting schedule — or remove this line]</li><li><strong>Benefits:</strong> [health cover, retirement plan, learning budget]</li><li><strong>Time off:</strong> [days per year] plus public holidays</li></ul><h2>Conditions</h2><p>This offer is contingent on [successful completion of a background check, proof of your right to work in [Country], and signature of our standard confidentiality agreement]. Your employment will be governed by the employment agreement enclosed with this letter.</p><h2>Accepting the Offer</h2><p>To accept, please sign below and return this letter by <strong>[Expiry Date]</strong>. If any questions come up before then, reach me directly at [email or phone] — we would love to have you aboard.</p><p>Warm regards,<br /><strong>[Hiring Manager Name]</strong><br />[Title], [Company Name]</p><p><strong>Accepted by:</strong> [Candidate Full Name]<br />Signed: ______________________<br />On: [Date]</p>`,
  },
  {
    id: "resume",
    name: "Resume",
    description: "One-page resume that leads with impact: profile, skills, history, projects.",
    icon: "user",
    html: `<h1>[Full Name]</h1><p>[Target Job Title] · [Location] · [Email Address] · [Phone Number] · [linkedin.com/in/username]</p><h2>Profile</h2><p>[Three lines at most: the role you excel at, the proof — years, domains, a headline win — and the value you bring to your next team.]</p><h2>Core Skills</h2><ul><li><strong>[Category, e.g. Languages]:</strong> [Skill], [Skill], [Skill]</li><li><strong>[Category, e.g. Frameworks &amp; Tools]:</strong> [Skill], [Skill], [Skill]</li><li><strong>[Category, e.g. Practices]:</strong> [Skill], [Skill]</li></ul><h2>Work History</h2><h3>[Role] · [Company]</h3><p><em>[Month Year] – [Present] · [City / Remote]</em></p><ul><li>[Led, built, or shipped X, resulting in Y — quantify the outcome wherever possible.]</li><li>[A second accomplishment framed as action then result, not a list of duties.]</li><li>[A third bullet showing scope: team size, budget, users, or scale.]</li></ul><h3>[Previous Role] · [Company]</h3><p><em>[Month Year] – [Month Year] · [City]</em></p><ul><li>[Accomplishment with a concrete number attached.]</li><li>[Accomplishment that shows growth toward your target role.]</li></ul><h2>Selected Projects</h2><ul><li><strong>[Project name]</strong> — [one line on what it does and the tech or approach behind it].</li><li><strong>[Project name]</strong> — [why it is relevant to the role you want].</li></ul><h2>Education &amp; Certifications</h2><ul><li><strong>[Degree]</strong>, [Institution] — [Year]</li><li><strong>[Certification]</strong>, [Issuing body] — [Year]</li></ul>`,
  },
];

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id) || null;
}
